#!/usr/bin/env expect

set timeout 20
set key [lindex $argv 0]
set data [lindex $argv 1]
set file [lindex $argv 2]

if {[llength $argv] == 0} {
  send_user "Usage: testJsonData.exp.exp <key> <data> <file>\n";
  exit 1
}

spawn ./parseJsonFile -f$file -v$key

expect {
	 "$data" { send_user "Test: pass\n"; exit 0}
	eof { send_user "Test: fail -- wrong output!\n"; exit 1}
	timeout { send_user "Test: fail -- timeout!";  exit 1}
}

