.TH LIBJPARSE 3 "SEPTEMBER 2014" Unix "User Manuals"                                  
.SH NAME                                                                     
getArrayElements -- gets the elements of an array of unstructured data type
.SH LIBRARY                                                                 
.B Standard C Library (libjparse, -ljparse)
.SH SYNOPSIS                                                                 
.B      #include <parseJsonConfig.h>

.B	node* getArrayElements(node* arrayRootElement);
.SH DESCRIPTION                                                              
The getArrayElements() function recursively gets the elements of an array of unstructured data type. The first call of this funtion must specify that array with the parameter 
.I arrayRootElement.
The following calls of getArrayElements() must specify 
.I NULL
as parameter to fetch the remaining elements of the array.
.SH RETURN VALUES
The getArrayElements() function returns a pointer of the n-element of the array or NULL.
A NULL value returned means that no more elements are available or that an error was present. In case of errors, the
.I errno
variable will contain one of the values:
.I ERR_WRONG_NODE_TYPE
.I ERR_WRONG_INITIAL_NODE
.I ERR_UNHANDLED_NODE_TYPE
.I ERR_NO_MORE_ELEMENTS
.SH SEE ALSO                                                                  
getElementValueByString(3), getArrayElements(3), getArrayOfObjsElements(3), getElementFromObj(3), isScalar(3), libjparse(3), parseJsonConfig(3)
.SH STANDARDS
Todo.
.SH BUGS                                                                     
This program is a beta, if some bugs are present, they will be removed in the stable relase.
.SH AUTHOR                                                                   
Gabriele Bonacini <gabriele.bonacini@protonmail.com>                            
