.TH LIBJPARSE 3 "SEPTEMBER 2014" Unix "User Manuals"                                  
.SH NAME                                                                     
parseJsonConfig -- parse a JSON file and load the data in a in-memory indexed structure.
.SH LIBRARY                                                                 
.B Standard C Library (libjparse, -ljparse)
.SH SYNOPSIS                                                                 
.B      #include <parseJsonConfig.h>

.B	int parseJsonConfig(char* configPath, node* nodeRoot, pathIndex** fullIndexesList);
.SH DESCRIPTION                                                              
The parseJsonConfig() function parse a JSON file and load the data in a in-memory indexed structure.
The function needs, as parameters, the full path of the JSON file (
.I configPath 
), a pointer to a node element (
.I nodeRoot 
) that is the root element of the structure ( see libjparse(3)) and a pathIndex** (
.I fullIndexesList 
) that is the handler to the index.
At moment the JSON must contain less than 1024 nesting levels about the "object" elements.
.SH RETURN VALUES
The getArrayOfObjsElements() function returns the number of the elements processed or one of these error codes:
.I NO_PARSE_ERR
.I NO_CONFIG_FILE_ERR
.SH SEE ALSO                                                                  
getElementValueByString(3), getArrayElements(3), getArrayOfObjsElements(3), getElementFromObj(3), isScalar(3), libjparse(3), parseJsonConfig(3)
.SH STANDARDS
Todo.
.SH BUGS                                                                     
This program is a beta, if some bugs are present, they will be removed in the stable relase.
.SH AUTHOR                                                                   
Gabriele Bonacini <g.random36@gmail.com>                            
